platform :ios, '8.0'

target 'UP2019' do

pod 'AFNetworking', '~> 3.2.1'
	pod "MJExtension", '~> 3.0.13'
	pod "SDWebImage"
	pod "Masonry", '~> 1.1.0'
	pod "MBProgressHUD", '~> 0.9.1'
	pod "MJRefresh", '~> 3.1.15.3'
	pod "IQKeyboardManager", '~> 6.0.3'
end
