# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YunisDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YunisDemo
	pod "Masonry"
  target 'YunisDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YunisDemoUITests' do
    # Pods for testing
  end

end
